dataset_relative_path: dataset/B301MM/high
model:
  ddgm:
    b1: 0.5
    b2: 0.999
    batch_size: 64
    channels: 1
    dataset_name: aapm
    decay_epoch: 100
    epoch: 0
    img_size: 512
    lambda_cyc: 3.0
    lambda_id: 2.0
    latent_dim: 100
    lr: 0.0002
    n_cpu: 16
    n_residual_blocks: 9
project_dir: /root/lmy/GanZoo
train:
  batch_size: 48
  checkpoint_interval: 2000
  gpu_id: '6'
  img_size: 256
  max_nums: 4000
  n_epochs: 200000
  print_interval: 500
  sample_interval: 2000
  use_wandb: true
train_dpsb:
  batch_size: 48
  checkpoint_interval: 2000
  gpu_id: '5'
  img_size: 256
  max_nums: 4000
  n_epochs: 200000
  print_interval: 100
  sample_interval: 2000
  use_wandb: true
train_dpsb_mddi:
  batch_size: 48
  checkpoint_interval: 2000
  gpu_id: '4'
  img_size: 256
  max_nums: 4000
  n_epochs: 200000
  print_interval: 100
  sample_interval: 2000
  use_wandb: true
