dataset_relative_path: dataset/B301MM/high
model:
  gan:
    b1: 0.5
    b2: 0.999
    channels: 1
    img_size: 256
    latent_dim: 100
    lr: 0.0002
    n_cpu: 8
project_dir: /Users/zane/PycharmProjects/GanZoo
project_name: test
train:
  batch_size: 256
  epochs: 2000
  gpu_id: 1
  sample_interval: 400
